import { Hono } from 'hono';
import { projectRoommate } from '@con-sign/shared';
import type { Env } from '../types.js';
import { HttpError } from '../errors.js';
import { getOrCreatePairCode } from '../auth/pair-code.js';
import {
  getDevice,
  getRoom,
  getVisibility,
  listRoommatesForRoom,
  roommateRowToApi,
  touchDevice,
} from '../db/queries.js';
import {
  computeConDay,
  renderRevokedSvg,
  renderSignSvg,
  renderUnpairedSvg,
} from '../render/sign.js';

export const deviceRoutes = new Hono<Env>();

const SVG_HEADERS = {
  'Content-Type': 'image/svg+xml; charset=utf-8',
  // Short cache: panels self-throttle their refresh rate, but the unpaired
  // code rotates every 5 min and we don't want a CDN to pin the old one.
  'Cache-Control': 'no-store',
};

/**
 * GET /api/device/sign.png
 *
 * Bearer is the device's persistent UUID (generated by firmware on first
 * boot, used forever). Three render branches:
 *
 *   - row absent           → unpaired panel with rotating 6-char pair code
 *   - row.room_id present  → paired panel for that room (existing behavior)
 *   - row.revoked_at set   → "panel unpaired" notice
 *
 * Width/height query params let firmware request the panel's native size.
 */
deviceRoutes.get('/sign.png', async (c) => {
  const auth = c.req.header('Authorization');
  const m = auth?.match(/^Bearer (.+)$/);
  if (!m) throw new HttpError(401, 'missing_bearer');
  const deviceId = m[1]!.trim();
  if (!deviceId) throw new HttpError(401, 'missing_bearer');

  const widthQ = c.req.query('w');
  const heightQ = c.req.query('h');
  const width = widthQ ? Math.max(100, Math.min(4096, Number(widthQ))) : 800;
  const height = heightQ ? Math.max(100, Math.min(4096, Number(heightQ))) : 480;

  const device = await getDevice(c.env.DB, deviceId);

  // Unpaired (no row, or row exists but neither paired nor revoked — the
  // re-pair-after-revoke transition leaves a row with both fields cleared).
  if (!device || (!device.room_id && !device.revoked_at)) {
    const code = await getOrCreatePairCode(c.env.SESSIONS, deviceId);
    return new Response(renderUnpairedSvg({ pairCode: code, width, height }), {
      headers: SVG_HEADERS,
    });
  }

  // Touch last_seen for any device the server already knows about.
  await touchDevice(c.env.DB, deviceId);

  if (device.revoked_at) {
    return new Response(renderRevokedSvg({ width, height }), { headers: SVG_HEADERS });
  }

  // Paired — fetch the room + roommates and render at GUEST tier.
  const room = await getRoom(c.env.DB, device.room_id!);
  if (!room) throw new HttpError(404, 'room_not_found');

  const conRow = await c.env.DB.prepare('SELECT start_date FROM con WHERE id = ?')
    .bind(room.con_id)
    .first<{ start_date: string | null }>();

  const rows = await listRoommatesForRoom(c.env.DB, room.id);
  const projected = await Promise.all(
    rows.map(async ({ row, avatarUrl }) => {
      const visibility = await getVisibility(c.env.DB, row.id);
      const r = roommateRowToApi(row, avatarUrl);
      return projectRoommate(r, visibility, []);
    }),
  );

  const svg = renderSignSvg({
    roomName: room.name,
    roommates: projected,
    width,
    height,
    conDay: computeConDay(conRow?.start_date ?? null),
  });
  return new Response(svg, { headers: SVG_HEADERS });
});
