/**
 * Pair-code OTP for device bootstrap.
 *
 * An unpaired e-ink panel polls the device endpoint with its persistent
 * `device_id` (UUID generated by the firmware). The server mints a random
 * 6-character code, stores it in KV under two keys (5-minute TTL), and
 * returns it for the panel to render. An admin types the code into the
 * dashboard; the server reverse-looks up the device_id and inserts a
 * `device` row binding it to the admin's room.
 *
 * Code alphabet excludes ambiguous characters (no I/O/0/1) so panels can
 * print at large size and humans can type without confusion. 32 chars × 6
 * positions = ~10⁹ codes; collisions at 10–100 simultaneous unpaired
 * devices are negligible, but we still check for them on insert.
 */

const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const CODE_LEN = 6;
export const PAIR_CODE_TTL_SEC = 300;
const COLLISION_RETRIES = 8;

const codeKey = (code: string): string => `pair:code:${code}`;
const deviceKey = (deviceId: string): string => `pair:dev:${deviceId}`;

export function generatePairCode(): string {
  const buf = crypto.getRandomValues(new Uint8Array(CODE_LEN));
  let out = '';
  for (let i = 0; i < CODE_LEN; i++) {
    out += ALPHABET[buf[i]! % ALPHABET.length];
  }
  return out;
}

export function normalizePairCode(input: string): string {
  // Admins may type with spaces or in lowercase; mockup displays with spaces.
  return input.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

/**
 * Return the device's currently active pair code, minting one if none
 * exists or the previous one has expired. Idempotent across polls — the
 * panel can refresh as fast as it likes without churning the displayed
 * code mid-window.
 */
export async function getOrCreatePairCode(
  kv: KVNamespace,
  deviceId: string,
): Promise<string> {
  const existing = await kv.get(deviceKey(deviceId));
  if (existing) return existing;

  for (let attempt = 0; attempt < COLLISION_RETRIES; attempt++) {
    const code = generatePairCode();
    const collision = await kv.get(codeKey(code));
    if (collision) continue;
    await kv.put(codeKey(code), deviceId, { expirationTtl: PAIR_CODE_TTL_SEC });
    await kv.put(deviceKey(deviceId), code, { expirationTtl: PAIR_CODE_TTL_SEC });
    return code;
  }
  throw new Error('pair_code_alphabet_exhausted');
}

/**
 * Look up the device behind a pair code and atomically invalidate it so the
 * code can't be reused. Returns null if the code is unknown or expired.
 */
export async function consumePairCode(
  kv: KVNamespace,
  rawCode: string,
): Promise<string | null> {
  const code = normalizePairCode(rawCode);
  if (code.length !== CODE_LEN) return null;
  const deviceId = await kv.get(codeKey(code));
  if (!deviceId) return null;
  await Promise.all([kv.delete(codeKey(code)), kv.delete(deviceKey(deviceId))]);
  return deviceId;
}
